### ISSUE TITLE
IConfigurationRoot from ctor isn't being used?

### ISSUE THREAD

**Issue by mkontula** [zyborg/LogentriesDotNet#4]
Correct me if I'm wrong, but looking at the code in ctor, is the `IConfigurationRoot config` parameter being used at all?

https://github.com/zyborg/LogentriesDotNet/blob/master/src/Zyborg.Logentries/LogentriesAsyncLogger.cs#L125

**Comment by ebekker** [comment]
You are right, there was a missing assignment, it's been corrected.
